### PR TITLE
add: Login via CoSign

### LINKED ISSUE #8: Cosign login

### PR DESCRIPTION
**Pull request by mrshu**
* Ensure the auth endpoints are covered by CoSign authentification.

* Fixes #8

Signed-off-by: mr.Shu <mr@shu.io>

### CODE REVIEW

**Comment by mrshu** [comment]
@danshaman05 @Adman There are a few things to figure out in here:

- This essentially requires an Apache server for deployment. Normally, I'd check whether the application is running in the "debug" mode but I was not sure how to do that here -- any input would be greatly appreciated
- It is not obvious what to do with the hardcoded strings -- we are probably OK with them being in there this way for now but in the long term we'd probably like to have some internationalization set up so that they can get easily translated
- It seems like the `login()` function is using quite long lines -- I believe it would be best to clean them up, as well as the comments
- Supporting flash messages seems to be "in the works" -- was the any reason why they ended up being commented out?

I guess this is one part of the codebase where I am OK with just a few (if any) tests :)

**Comment by Adman** [comment]
Regarding point 1, have you tried `export FLASK_DEBUG=true` ? (I think `true` should be default)

Could we maybe set up instance of this on svt2 server similarly to beta instance, under for example `/candle-ng` url?

**Comment by mrshu** [comment]
Thanks @Adman. What I meant with regards to 1. is that while I can certainly turn the Flask's debug mode on, I am not sure how to get that information within the blueprint.

Do you happen to know anything about that?

**Comment by Adman** [comment]
Would something like [this](https://flask.palletsprojects.com/en/1.1.x/api/#flask.current_app) work?
https://stackoverflow.com/a/38262792/1442465

**Comment by mrshu** [comment]
@Adman right, that should probably work but I am not sure how will this reflect the following:

https://github.com/fmfi-svt/candle-ng/blob/7536e84de21b09fee9dac1effefb7c1142f62120/candle/config.py#L14-L20

Hence, I wanted to hear @danshaman05's view on that.

**Comment by danshaman05** [comment]
@mrshu
> Supporting flash messages seems to be "in the works" -- was the any reason why they ended up being commented out?

As far as I know, flash-messages are rendered to HTML, so they will break up our 1:1 testing... Or am I getting something wrong with your 1:1 idea? 

> It seems like the login() function is using quite long lines -- I believe it would be best to clean them up, as well as the comments

Can I clean them up in a new commit and add it to this PR?

> It is not obvious what to do with the hardcoded strings -- we are probably OK with them being in there this way for now but in the long term we'd probably like to have some internationalization set up so that they can get easily translated

So do I understand correctly that you want to allow the user to "switch to English" for example, right? If yes, it sounds good, but I can start with this later...

**Comment by mrshu** [comment]
> As far as I know, flash-messages are rendered to HTML, so they will break up our 1:1 testing... Or am I getting something wrong with your 1:1 idea?

Right, you are very much right. No need for a specific action here, it was just a question :)

> Can I clean them up in a new commit and add it to this PR?

Please feel free to (or use a different PR), I don't really have a strong view here :)

> So do I understand correctly that you want to allow the user to "switch to English" for example, right? If yes, it sounds good, but I can start with this later...

Right, again, more of a comment than anything -- feel free to ignore it for now :)

**Comment by danshaman05** [comment]
@mrshu 
> This essentially requires an Apache server for deployment. Normally, I'd check whether the application is running in the "debug" mode but I was not sure how to do that here -- any input would be greatly appreciated

since Flask1.0 you can use "ENV" value to test, if you are in the "production" or "development" environment: 
```python
from flask import current_app
if current_app.config['ENV'] == "production":
    do_something ...
```
This configuration value should be set in .env file (I have already added instructions to README in last commit).

https://flask.palletsprojects.com/en/1.1.x/config/#ENV
https://sites.uclouvain.be/P2SINF/flask/server.html#command-line

**Comment by mrshu** [comment]
Thanks @danshaman05, should be reflected in the latest version.

Feel free to merge it in, if you are OK with it.

**Pull request merged**
